spring:
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/CRM?autoReconnect=true
    username: root
    password: root
    flyway:
      baselineOnMigrate: true
      validateOnMigrate: false
  jpa:
    generate-ddl: false
    show-sql: true
  hibernate:
    ddl-auto: none

server:
  port: 3000
  servlet:
    context-path: /
    session:
      timeout: 30m

vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
